name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v6

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Set up variables
      id: vars
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}"
        echo "image_name=${IMAGE_NAME}" >> $GITHUB_OUTPUT
        echo "tag=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ steps.vars.outputs.image_name }}:${{ steps.vars.outputs.tag }}
          ${{ steps.vars.outputs.image_name }}:latest
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64/v8
